# Chapter 4. NumPy Basics: Arrays and Vectorized Computation

*NumPy* is the *lingua francas* of numerical data exchange in the Python data science ecosystem:
- `ndarry` is an efficient multidimensional array with fast computing abilities
- tools for reading/writing array data to disy and working with memory-mapped files
- Linear algebra, random number generation, and FFT
- A C-API

In this chatper, we will learn some important data analysis using NumPy:
- `ndarry` arithmetic, indexing, slicing, Boolean and fancy indexing, transposing
- Pseudorandom number generation
- Universal Functions (`ufunc`)
- Array-oriented programming
- File I/S with arrays
- Linear algebra
- An example—random walks

In [ ]:
# Let's practice with ndarry
import numpy as np

data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]])

# Three key attributes: ndim, shape, dtype
data.shape # (2, 3)
data.dtype # dtype('float64')
data.ndim # 2

2

In [ ]:
# Creating ndarry
data1 = [6, 7, 8, 1, 2, 4]
data1_array = np.array(data1)
data1_array # array([6, 7, 8, 1, 2, 4])

# reshape
data1_array = data1_array.reshape(2, 3)
data1_array.shape # (2, 3)

# special functions to create ndarray
np.zeros(10)
np.ones((2, 3))
np.empty((2, 3, 4)) # filling with random tiny numbers
np.arange(8)

array([3, 3])

In [ ]:
data1 = [6, 7, 8, 1, 2, 4]
data1_array = np.array(data1)
data1_asarray = np.asanyarray(data1)

array([6, 7, 8, 1, 2, 4])

In [34]:
import math
np.full((2,3), math.pi, dtype=np.int16)

array([[3, 3, 3],
       [3, 3, 3]], dtype=int16)

### NumPy Array Creation Functions

| Function | Description |
|----------|-------------|
| `array` | Convert input (list, tuple, array, or other sequence type) to an ndarray; copies the input data by default |
| `asarray` | Similar to `array` but do not copy if the input is already an ndarray |
| `arange` | Similar to `range` but returns an ndarray instead of a list |
| `ones`, `ones_like` | Produce an array of 1's |
| `zeros`, `zeros_like` | Produce an array of 0's |
| `empty`, `empty_list` | Produce an array of random tiny numbers |
| `full`, `full_like` | Produce an array of one specified number |
| `eye`, `identify` | Produce an $N \times N$ identify matrix |

### NumPy Data Types (`dtype`)

The most common `dtypes` include:

| Type | Type Code | Description |
|------|-----------|-------------|
| `int32`, `uint32` | `i4`,`u4` | Signed and unsigned 32-bit integer types |
| `float64` | `f8` or `d` | Standard double-precision floating point; compatible with C double and Python `float` object |
| `bool` | `?` | Boolean type: `True` or `False` |
| `object` | `O` | Python object |
| `str_` | `S` | Fixed-length ASCII string type |
| `bytes` | `U` | Fixed-length Unicode type |

*Type casting*: You can convert or *cast* an array from one data type to another with `astype` method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype # dtype('int64')

arr_float = arr.astype(np.float64)
arr_float.dtype # dtype('float64')

import math
arr2 = np.full((2, 3), math.pi)
arr2_int = arr2.astype(np.int32)

arr3 = np.array(["1.2", "3.5", "5"], dtype=np.str_)
arr3_float = arr3.astype(np.float64)
arr3_float # array([1.2, 3.5, 5. ])

array([1.2, 3.5, 5. ])

### Arithmetic with NumPy Arrays

Arithmetic operations are vectorized in NumPy, so they are fast and efficient. All arithmetic operations are done element-wise, with broadcasting rules.

In [62]:
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.array([[0, 4., 1.], [7, 2, 12]])
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [72]:
# Review: list slicing & assignment
my_list = [1, 2, 3, 4, 5, 6]
my_list[2:4] = [100, 100]

# Array slicing and assignment
arr1 = np.arange(1, 7)
arr1[2:4] = 100 # array([  1,   2, 100, 100,   5,   6])


> One key difference between np.array and Python (or R) is that array slicing are views on the original array. Therefore, even if you re-assign the array to another name, changes the new array are still reflected in the original array. If you want to keep the original array intact, you need to use `new_array = original_array.copy()`.

In [ ]:
arr1 = np.arange(1, 7)
new_arr = arr1
new_arr[2:4] = 100
print(arr1) # [  1   2 100 100   5   6]

# To add your original array intact
new_arr2 = arr2.copy()
new_arr2[0] = 99
print(arr1) # [  1   2 100 100   5   6]

[  1   2 100 100   5   6]
[  1   2 100 100   5   6]


In [ ]:
# Indexing/slicing higher dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0] # row selection
arr2d[:,1] # col selection
arr2d[0][1] # element selection
arr2d[0, 1] # same as above

np.int64(2)

In [96]:
# Multi-dimensional array slicing
arr3d = np.arange(1, 13).reshape(2, 2, 3)
original = arr3d[0][1].copy()
arr3d[0][1] = 100
arr3d[0][1] = original
original.ndim


1

> Note: With slicing, if you use a single integer, it drops that dimension; while if you use slicing (e.g., `1:2`), that dimension is preserved (although it can be $1$).

In [ ]:
# The difference between indexing and slicing 
arr2d = np.arange(1, 13).reshape(3, 4)
arr2d_dropdim = arr2d[0, 1:3] # array([2, 3])
arr2d_dropdim.shape # (2,) 
arr2d_dropdim.ndim # 1

arr2d_presdim = arr2d[0:1, 1:3] # array([[2, 3]])
arr2d_presdim.shape # (1, 2)
arr2d_presdim.ndim # 2

2

### Boolean Indexing

In [122]:
names = np.array(['Bob', 'Joe', 'Adam', 'Bob', 'Chris'])
data = np.arange(1, 16).reshape(5, 3)

# select when name is Bob
data[names == 'Bob']

# select name is not Bob—equivalent approaches
data[names == 'Bob']
data[~(names == 'Bob')]

condition = names == "Bob"
data[~condition]

# If you need and (&), or (|)
data[(names == "Bob") | (names == "Joe"), 1:3]

array([[ 2,  3],
       [ 5,  6],
       [11, 12]])

In [ ]:
arr2d = np.arange(1, 13).reshape(3, 4)

# negative indexing
arr2d[:, -1] # array([ 4,  8, 12])

# note the difference of single vs double square brackets
arr2d[1, 2] # one element, 7
arr2d[[1, 2]] # rows 1 & 2: shape (2,4)

# fancy indexing
arr2d[:, [3, 1]] # shape (3,2)
arr2d[[0, 2], [1, 3]] # two elements (0,1) and (2,3) -> array([ 2, 12])

array([ 2, 12])

In [139]:
# To transpose, you can use either .T or .transpose()
arr2d.T
arr2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
# Matrix dot product—equivalent approaches
arr2d @ arr2d.T
np.dot(arr2d, arr2d.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [142]:
# Transpose is a special case of swapaxes
arr2d.swapaxes(0, 1)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Pseudorandom Number Generation

The `numpy.random` module supplements the built-in Python `random` module with fast array random number generation.

Although you could use functions such as `np.random.standard_normal(size=(n,m))`, it's considered best practice to create a generator first with `rng = np.random.default_rng(seed=42)`. The generator object `rng` is also isolated from other code which might use the `nuumpy.random` module.

Some common random number generator methods:
- `permutation` returns a random permutation of a sequence
- `shuffle` randomly permutes a sequence in place
- `uniform` draws sample from a uniform distribution
- `integers` draws random integers from a given low-to-high range
- `standard_normal` draws from a standard normal distribution
- `normal` draws from a normal distribution
- `uniform` draws samples from a uniform (0,1) distribution

In [143]:
from random import normalvariate
N = 1_000_000
%timeit sample = [normalvariate(0, 1) for _ in range(N)]

346 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [144]:
%timeit np.random.standard_normal(N)

15.1 ms ± 54.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# Create a generator
rng = np.random.default_rng(seed=42)
type(rng) # numpy.random._generator.Generator

numpy.random._generator.Generator

In [ ]:
# Let's give it a try
random_data = rng.standard_normal((2, 3)) # note the double parenthesis

array([[ 0.1278404 , -0.31624259, -0.01680116],
       [-0.85304393,  0.87939797,  0.77779194]])

In [152]:
out = np.zeros_like(arr2d)
out

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Universal Functions: Fast Element-Wise Array Functions

A *universal* function or *ufunc* is a function that performs element-wise array operations on ndarrys.

Common *unary* ufuncs:
- `abs` and `fabs` compute absolute values
- `sqrt` and `square` compute square root and square
- `exp` computes exponential $e^{x}$
- `log`, `log10`, `log2`, and `log1p` represent natural log ($e$), $log_{10}$, $log_{2}$ and $log(1+x)$
- `sign` compute the sign of each element: `1` (pos), `0`, and `-1` (neg)
- `ceil` and `floor`
- `rint` rounds to the nearest integer
- `modf` returns fractional and integer parts of array
- `isnan` returns Boolean array indicating whether each element is `NaN`
- `isfinite`, `isinf` returns whether each element is finite or infinite, respectively
- `logical_not` is equivalent to `~arr`

Common binary ufuncs:
- `add`, `subtract`, `multiply`, `divide`, `floor_divide`, `power`
- `maximum`, `fmax`, `minimum`, `fmin`, `mod`
- `copysign`
- `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal`
- `logical_and` (&), `logical_or` (|), `logical_xor` (^)


In [158]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print(f"X = {X}")
print(f"Y = {Y}")

X = [[1 2 3]
 [1 2 3]]
Y = [[4 4 4]
 [5 5 5]]
